Feature/wsdev 870 card placeholder merge
cuweb/rds-beta pull request #64
Opened 2022-02-25 00:40 UTC by Singh-Ish

Adding placeholder for people card and figure 
- written test for the same 

Jira Ticket No: WSDEV 870

2022-02-25 14:28 UTC, marceloglacial requested changes

2022-02-25 14:44 UTC, HanqingZhou commented
Great job!

2022-02-25 17:35 UTC, Singh-Ish commented on src/components/Card/components/FigureVariantCard.tsx
> +                {description ? (
Removed the description condition from the figure card variant

2022-02-25 17:38 UTC, Singh-Ish commented on src/components/CardPeople/CardPeople.stories.tsx
> +import data from './CardData.json'
sorry Marcelo i have changed the name of the source file to card people's data as it has data related to people card only

2022-03-02 13:00 UTC, marceloglacial requested changes

2022-03-02 13:00 UTC, marceloglacial commented on src/components/Card/Card.stories.tsx
>  }
Please fix lint errors

2022-03-02 13:06 UTC, marceloglacial commented on src/components/Card/Card.stories.tsx
>  }
Check the button CTA stories

2022-03-02 13:20 UTC, Singh-Ish commented on src/components/Card/components/FigureVariantCard.tsx
>          <LinkWrapper link={link}>
Made the changes

2022-03-02 13:21 UTC, Singh-Ish commented on src/components/CardPeople/CardPeople.stories.tsx
> +    title: `Components/Card People`,
Moved the people card story under card

2022-03-02 13:21 UTC, Singh-Ish commented on src/components/CardPeople/CardPeople.stories.tsx
> +PeopleCard.args = {
change the name to base story under people card

2022-03-02 13:22 UTC, Singh-Ish commented on src/components/CardPeople/CardPeople.stories.tsx
> +PeopleCardWithNoImage.args = {
change the name to "WithNoImage" story under people card

2022-03-02 13:22 UTC, Singh-Ish commented on src/components/Card/Card.stories.tsx
>  }
fixed the lint error

2022-03-08 16:24 UTC, marceloglacial approved these changes

2022-03-08 16:24 UTC, merged